import { chromium } from 'playwright';
import { createServer } from 'http';
import { readFileSync, existsSync, statSync } from 'fs';
import { join, extname } from 'path';
const ROOT=new URL('./dist/',import.meta.url).pathname;
const MIME={'.html':'text/html','.js':'text/javascript','.css':'text/css','.png':'image/png','.svg':'image/svg+xml','.webmanifest':'application/manifest+json','.json':'application/json'};
const server=createServer((q,s)=>{let p=join(ROOT,decodeURIComponent(q.url.split('?')[0]));if(!existsSync(p)||statSync(p).isDirectory())p=join(ROOT,'index.html');s.writeHead(200,{'Content-Type':MIME[extname(p)]??'application/octet-stream'});s.end(readFileSync(p));});
await new Promise(r=>server.listen(4339,r));
const b=await chromium.launch({executablePath:'/opt/pw-browsers/chromium-1194/chrome-linux/chrome',args:['--no-sandbox']});
const page=await (await b.newContext({viewport:{width:1440,height:1200},deviceScaleFactor:2})).newPage();
await page.goto('http://localhost:4339/',{waitUntil:'domcontentloaded'}); await page.waitForTimeout(1500);
await page.getByRole('button',{name:'Nutrition',exact:true}).first().click(); await page.waitForTimeout(900);
await page.getByRole('button',{name:'Rebuild'}).click(); await page.waitForTimeout(900);
const t=await page.locator('main').innerText();
const meals=[...t.matchAll(/\n(BREAKFAST|LUNCH|SNACK|DINNER)[\s\S]{0,140}?\n(.+?)\n(\d+) kcal\s+(\d+) g protein/g)].map(m=>`${m[1]}: ${m[2].trim()} — ${m[3]} kcal / ${m[4]} g P`);
console.log(meals.join('\n'));
const protein = [...t.matchAll(/(\d+) g protein/g)].map(m=>+m[1]).slice(0,4).reduce((a,b)=>a+b,0);
console.log('plan protein total:', protein, '| protein remaining target:', t.match(/(\d+) \/ 130 g/)?.[1]);
console.log('planned line:', t.match(/(\d+) KCAL PLANNED.*/i)?.[0]);
await page.screenshot({path:'nut-plan2.png', fullPage:false});
await b.close(); server.close();
