import { chromium } from 'playwright';
import { createServer } from 'http';
import { readFileSync, existsSync, statSync } from 'fs';
import { join, extname } from 'path';
const ROOT=new URL('./dist/',import.meta.url).pathname;
const MIME={'.html':'text/html','.js':'text/javascript','.css':'text/css','.png':'image/png','.svg':'image/svg+xml','.webmanifest':'application/manifest+json','.json':'application/json'};
const server=createServer((q,s)=>{let p=join(ROOT,decodeURIComponent(q.url.split('?')[0]));if(!existsSync(p)||statSync(p).isDirectory())p=join(ROOT,'index.html');s.writeHead(200,{'Content-Type':MIME[extname(p)]??'application/octet-stream'});s.end(readFileSync(p));});
await new Promise(r=>server.listen(4338,r));
const b=await chromium.launch({executablePath:'/opt/pw-browsers/chromium-1194/chrome-linux/chrome',args:['--no-sandbox']});
const page=await (await b.newContext({viewport:{width:1440,height:980},deviceScaleFactor:2})).newPage();
await page.goto('http://localhost:4338/',{waitUntil:'domcontentloaded'}); await page.waitForTimeout(1500);
const go=async n=>{await page.getByRole('button',{name:n,exact:true}).first().click();await page.waitForTimeout(800);};
await go('Nutrition');
const t=await page.locator('main').innerText();
console.log('home water:', t.match(/([\d.]+) of [\d.]+ litres/i)?.[1], 'L');
console.log('eaten today:', t.match(/eaten (\d+) kcal/i)?.[1], 'kcal of', t.match(/target (\d+)/i)?.[1]);
await page.screenshot({path:'nut-home2.png'});
await go('Body & intake'); await page.waitForTimeout(900);
const p2=await page.locator('main').innerText();
console.log('avg intake:', p2.match(/average intake\s*\n\s*(\d+)/i)?.[1], '| avg protein:', p2.match(/average protein\s*\n\s*(\d+)/i)?.[1], '| on target:', p2.match(/days on target\s*\n\s*([\d/]+)/i)?.[1], '| consistency:', p2.match(/(\d+)\s*\n?\s*\/ 100/)?.[1]);
await page.screenshot({path:'nut-progress3.png'});
await b.close(); server.close();
