import { chromium } from 'playwright';
import { createServer } from 'http';
import { readFileSync, existsSync, statSync } from 'fs';
import { join, extname } from 'path';
const ROOT=new URL('./dist/',import.meta.url).pathname;
const MIME={'.html':'text/html','.js':'text/javascript','.css':'text/css','.png':'image/png','.svg':'image/svg+xml','.webmanifest':'application/manifest+json','.json':'application/json'};
const server=createServer((q,s)=>{let p=join(ROOT,decodeURIComponent(q.url.split('?')[0]));if(!existsSync(p)||statSync(p).isDirectory())p=join(ROOT,'index.html');s.writeHead(200,{'Content-Type':MIME[extname(p)]??'application/octet-stream'});s.end(readFileSync(p));});
await new Promise(r=>server.listen(4340,r));
const b=await chromium.launch({executablePath:'/opt/pw-browsers/chromium-1194/chrome-linux/chrome',args:['--no-sandbox']});
const page=await (await b.newContext({viewport:{width:1280,height:1000},deviceScaleFactor:2})).newPage();
const errs=[]; page.on('pageerror',e=>errs.push(e.message));
await page.goto('http://localhost:4340/',{waitUntil:'domcontentloaded'}); await page.waitForTimeout(1500);
// wipe everything, then walk onboarding as a brand-new user
await page.getByRole('button',{name:'Settings',exact:true}).first().click(); await page.waitForTimeout(600);
await page.getByRole('button',{name:'Data & privacy'}).click(); await page.waitForTimeout(500);
await page.getByRole('button',{name:'Reset everything'}).click(); await page.waitForTimeout(500);
await page.getByRole('button',{name:'Delete everything'}).click(); await page.waitForTimeout(1200);
await page.getByRole('button',{name:'Nutrition',exact:true}).first().click(); await page.waitForTimeout(900);
console.log('onboarding shown:', /Let us start with you/.test(await page.locator('main').innerText()));
await page.screenshot({path:'nut-onboard.png'});
// fill step 1
await page.locator('input[placeholder="Your first name"]').fill('Ram');
const nums = page.locator('main input[type=number]');
await nums.nth(0).fill('24'); await nums.nth(1).fill('175'); await nums.nth(2).fill('72');
await page.waitForTimeout(500);
const t1 = await page.locator('main').innerText();
console.log('live BMI/BMR:', t1.match(/BMI\s*\n\s*([\d.]+)/)?.[1], '/', t1.match(/BMR\s*\n\s*(\d+)/)?.[1]);
const next = async () => { await page.getByRole('button',{name:'Continue'}).click(); await page.waitForTimeout(500); };
await next();
await page.getByRole('button',{name:/Fat loss/}).click(); await page.waitForTimeout(300); await next();
await page.getByRole('button',{name:/^Vegetarian/}).click(); await page.waitForTimeout(300); await next();
await page.getByRole('button',{name:'North Indian',exact:true}).click(); await next();
await next();
await page.getByRole('button',{name:/₹200–300/}).click(); await page.waitForTimeout(300); await next();
await page.getByRole('button',{name:/Gym/}).click(); await page.waitForTimeout(300); await next();
const t8 = await page.locator('main').innerText();
console.log('step 8 preview target:', t8.match(/Daily target\s*\n\s*(\d+)/)?.[1]);
await page.locator('input[type=checkbox]').check();
await page.locator('input[placeholder*="paneer, tomato"]').fill('paneer, atta, curd, onion');
await page.getByRole('button',{name:'Build my plan'}).click(); await page.waitForTimeout(1500);
const t9 = await page.locator('main').innerText();
console.log('plan built for new user:', /Today's plan/.test(t9), '| target:', t9.match(/target (\d+) kcal/i)?.[1]);
console.log('greeting:', t9.split('\n').find(l=>/Good (morning|afternoon|evening)|Still up/.test(l)));
await page.screenshot({path:'nut-newuser.png'});
console.log('errors:', errs.length, errs.slice(0,3).join(' | '));
await b.close(); server.close();
